# 7CS033 Assignment Task 1

### Complete the following tasks.

#### You should comment on your code where appropriate. Failing to add comments may result in a mark deduction.

#### You should write any explainations in the report cell if the task explicitly asks for this or if you wish to expand upon your solution.

#### Ensure you have ran your code cell and printed any of the required outputs. If necessary you can use more than one code cell.

### TASK 1.1: Write a code to receive an optional text, capitalise all words in the text and print them (2%)

In [3]:
############# WRITE THE CODE IN THIS CELL ####################
#Solution

# Ask the user to enter text (optional input)
# If the user just presses Enter, use a default sentence
text1 = input("Enter a sentence: ")

# Create an empty list to store capitalized words
output=[];

if text1 == "":
    text1 = "welcome to assessment one"

# Split the sentence into individual words
for word in text1.split():

    # Capitalize the first letter of each word
    capitalized_word= word.capitalize()

    # Add the capitalized word to the list
    output.append(capitalized_word)
    #print(word);

print(output)

# Join the words back into a full sentence
sentence = ' '.join(output);

# Print the final result
print("Capitalized Sentence:", sentence)

Enter a sentence:

['Welcome', 'To', 'Assessment', 'One']
Capitalized Sentence: Welcome To Assessment One

############ WRITE EXPLANATIONS HERE (IF APPLICABLE) #############

### TASK 1.2: Write a program that prompts the user to input the radius of a circle and calculates its area (2%)

In [6]:
############# WRITE THE CODE IN THIS CELL ####################

# Import the math module to use the value of pi
import math


# Prompt the user to enter the radius (allow decimal values)
inputRadius = float(input("Enter Radius of the circle: "))

# Calculate the area using the formula: πr²
circleArea = math.pi * (inputRadius ** 2)


# Display the result
print("The area of the circle is:", circleArea)

Enter Radius of the circle:  400.5

The area of the circle is: 503912.24703396624

############ WRITE EXPLANATIONS HERE (IF APPLICABLE) #############

### TASK 1.3: Download and import the 'adult' dataset from Canvas. Write a function to split the dataset column-wise into two halves and swap the first half with the second half (3%)

In [9]:
############# WRITE THE CODE IN THIS CELL ####################

import pandas as pd
import numpy as np

# Read the CSV file into a DataFrame
df = pd.read_csv('adult.csv');


# Define a function to split and swap columns
def swap_column_halves(df):

    # Get total number of columns
    num_cols = df.shape[1]
    
    # Find the midpoint of the columns
    mid = num_cols // 2
    
    # Split the columns into two halves
    first_half = df.iloc[:, :mid]
    second_half = df.iloc[:, mid:]
    
    # Swap the halves and concatenate them
    swapped_df = pd.concat([second_half, first_half], axis=1)

    return swapped_df



# Call the function
swapped_df = swap_column_halves(df)

# Display the swapped dataframe
swapped_df

,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income,age,workclass,fnlwgt,education,education-num,marital-status,occupation
0,Not-in-family,White,Male,2174,0,40,United-States,<=50K,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical
1,Husband,White,Male,0,0,13,United-States,<=50K,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial
2,Not-in-family,White,Male,0,0,40,United-States,<=50K,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners
3,Husband,Black,Male,0,0,40,United-States,<=50K,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners
4,Wife,Black,Female,0,0,40,Cuba,<=50K,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,Not-in-family,White,Female,0,0,36,United-States,<=50K.,39,Private,215419,Bachelors,13,Divorced,Prof-specialty
48838,Other-relative,Black,Male,0,0,40,United-States,<=50K.,64,NaN,321403,HS-grad,9,Widowed,NaN
48839,Husband,White,Male,0,0,50,United-States,<=50K.,38,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty
48840,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K.,44,Private,83891,Bachelors,13,Divorced,Adm-clerical
48841,Husband,White,Male,0,0,60,United-States,>50K.,35,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial

############ WRITE EXPLANATIONS HERE (IF APPLICABLE) #############

### Task 1.4: Write a function that takes the names of two numerical columns as input and compares their values for all rows. If the value in the first column is greater than the value in the second column, the function should return True; otherwise, it should return False. The function should append a new column to the dataset to store the comparison results for all rows. Apply the function to the 'age' and 'hours-per-week' columns in the adult dataset and print the resulting dataset (3%)

In [12]:
############# WRITE THE CODE IN THIS CELL ####################

df = pd.read_csv('adult.csv');



# Define a function that:
# 1. Takes a dataframe
# 2. Takes two numerical column names as input
# 3. Compares their values row-by-row
# 4. Appends a new column with True/False results
def isGreaterThan(dataframe, col1, col2):
    
    # Perform vectorized comparison:
    # Returns True if value in col1 > value in col2, otherwise False
    dataframe['isGreaterThan'] = dataframe[col1] > dataframe[col2]

    # Return the updated dataframe
    return dataframe

# Apply the function to compare 'age' and 'hours-per-week'
df = isGreaterThan(df, 'age', 'hours-per-week')

# Display the resulting dataset
df

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income,isGreaterThan
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,False
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,True
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,False
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,True
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K.,True
48838,64,NaN,321403,HS-grad,9,Widowed,NaN,Other-relative,Black,Male,0,0,40,United-States,<=50K.,True
48839,38,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K.,False
48840,44,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K.,True
48841,35,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K.,False

############ WRITE EXPLANATIONS HERE (IF APPLICABLE) #############

Task 1.1: Demonstrates string manipulation by capitalizing words in a sentence.<br/>
Task 1.2: Applies mathematical calculations to compute the area of a circle using user input.<br/>
Task 1.3: Performs dataframe column operations by splitting and swapping dataset columns.<br/>
Task 1.4: Uses functions and pandas operations to compare numerical columns and append logical (True/False) results to the dataset<br/>