# 7CS033 Workshop 1 Exercises

Complete all the exercises.

First, try to solve the questions independently, and then review the solutions. If you are struggling with a question, try using independant research to look for useful functions to help solve the problem. Ensure you understand the given solution to each problem before moving on to the next.

## Importing necessary Libraries

In [3]:
import pandas as pd
import numpy as np

## Python Warmup exercises

* Q1: Write a code that receives an optional text, print all letters in the text and store them in a list

In [1]:
#Solution:
output=[]
text1='''welcome to workshop 1'''
for i in text1:
    print(i)
    output.append(i)
print(output)

w
e
l
c
o
m
e

t
o

w
o
r
k
s
h
o
p

1
['w', 'e', 'l', 'c', 'o', 'm', 'e', ' ', 't', 'o', ' ', 'w', 'o', 'r', 'k', 's', 'h', 'o', 'p', ' ', '1']

* Q2: Write a code that receives an optional text, prints all words in the text and store them in a list

In [4]:
#Solution:
output=[]
text1='''welcome to workshop 1'''
for word in text1.split():
    print(word)
    output.append(word)
print(output)

welcome
to
workshop
1
['welcome', 'to', 'workshop', '1']

* Q3: Write Q2 answer as a function.

In [5]:
#Solution
text1='''welcome to workshop 1'''
def print_word(text):
    for word in text.split():
        print(word)
print_word(text1)

welcome
to
workshop
1

* Q4: Write a program to find out the average of a set of integers. The program prompts the user to enter the count of numbers

In [7]:
#Solution
count = int(input("Enter the count of numbers: ")) # This gets the count of numbers from the user and
# puts it in an integer variable
i = 0
sum = 0
for i in range(count):
    x = int(input("Enter an integer: "))
    sum = sum + x
avg = sum/count
print("The average is: ", avg)

Enter the count of numbers:  4
Enter an integer:  20
Enter an integer:  10
Enter an integer:  30
Enter an integer:  5

The average is:  16.25

* Q5: Write a program to check whether the given number is even or not.

In [8]:
#Solution
# If we divide an even number by 2, the remainder will be zero
number = input("Enter a number: ")
x = int(number)%2
if x == 0:
    print("The number is Even.")
else:
    print("The number is Odd.")

Enter a number:  5

The number is Odd.

* Q6: Write a program to find the average of 4 numbers using while loop. The program prompts the user to enter the numbers

In [9]:
#Solution
count = 0
sum = 0.0
while(count<4):
    number = float(input("Enter a real number: "))
    count=count+1
    sum = sum+number
avg = sum/4
print("Average is :",avg)

Enter a real number:  5
Enter a real number:  3
Enter a real number:  7
Enter a real number:  1

Average is : 1.6

* Q7: Write a function to find the average of a list of integers

In [10]:
#Solution
def give_me_average(in_list):
    count=len(in_list)
    sum=0
    for i in in_list:
        sum=sum+i
    avg = sum/count
    return avg
a=[1,2,3,4]
print("Average is :",give_me_average(a))

Average is : 2.5

* Q8: Write a program to display all integers within the range 100-120 whose sum of digits is an even number and store them in a list

In [11]:
#Solution
output=[]
for i in range(100,120):
    num = i
    sum = 0
    while(num!=0):
        digit = num%10
        sum = sum + digit
        num = num//10
    if(sum%2==0):
        output.append(i)
        print(i)
print(output)

101
103
105
107
109
110
112
114
116
118
[101, 103, 105, 107, 109, 110, 112, 114, 116, 118]

* Q9: Write a program to check whether the given integer is a multiple of both 5 and 7

In [13]:
#Solution
number = int(input("Enter an integer: "))
if((number%5==0)and(number%7==0)):
    print(number, "is a multiple of both 5 and 7")
else:
    print(number, "is not a multiple of both 5 and 7")

Enter an integer:  10

10 is not a multiple of both 5 and 7

## Pandas warmup exercises

• You can install Pandas on your system by using pip as follows:
pip install pandas

• You can import Pandas as follows:
import pandas

• Pandas is usually imported under the pd alias.
import pandas as pd

• You can check Pandas version as follows:
import pandas as pd
print(pd.__version__)

In [14]:
# You can use the DataFrame() method to create a Pandas DataFrame from a dictionary, numpy array, or a list.
data = {"calories": [420, 380, 390], "duration": [50, 40, 45]}
#load data into a DataFrame object:
df = pd.DataFrame(data)
print(df)
print('\n') # Addine an empty line to the end of the data frame
# ---
data = [[420, 380, 390],[50, 40, 45]]
df = pd.DataFrame(data)
print(df)

   calories  duration
0       420        50
1       380        40
2       390        45


     0    1    2
0  420  380  390
1   50   40   45

In [15]:
# You can use loc() or iloc() to return values, rows, or columns inside a data frame. Using loc() you need to specify the
# column name, but using iloc() you only need to specify the column index.
data = {"calories": [420, 380, 390], "duration": [50, 40, 45]}
#load data into a DataFrame object:
df = pd.DataFrame(data)
print(df)
print("\n")
print(df.loc[0,'calories'])
print("\n")
print(df.loc[0,:])
print("\n")
print(df.iloc[:,0])

   calories  duration
0       420        50
1       380        40
2       390        45


420


calories    420
duration     50
Name: 0, dtype: int64


0    420
1    380
2    390
Name: calories, dtype: int64

In [ ]:
# You can get the indices and columns names using index and column attributes as follows

data = {"calories": [420, 380, 390], "duration": [50, 40, 45]}
#load data into a DataFrame object:
df = pd.DataFrame(data)
index_names=list(df.index)
column_names=list(df.columns)
print(index_names,end='\n\n')
print(column_names)

In [16]:
# With the index and columns argument, you can name your own indexes and columns.
data = {
 "calories": [420, 380, 390],
 "duration": [50, 40, 45]
}
df = pd.DataFrame(data, index = ["day1", "day2", "day3"])
print(df)

      calories  duration
day1       420        50
day2       380        40
day3       390        45

In [17]:
# With the index argument, you can name your own indexes and columns
data =[[420, 380, 390],[50, 40, 45]]
df = pd.DataFrame(data, columns = ["c1", "c2", "c3"])
print(df)

    c1   c2   c3
0  420  380  390
1   50   40   45

## Importing a dataset for this workshop

## Importing the dataset directly from the source

In [ ]:
# Installing a package which is needed to download the dataset from its online source. This package is recommended by the online source at the following
# URL : https://archive.ics.uci.edu/dataset/2/adult
!pip3 install ucimlrepo

In [ ]:
# Downloading the dataset from the online source. The first two lines are given by the online source mentioned above
from ucimlrepo import fetch_ucirepo
# fetch dataset
adult = fetch_ucirepo(id=2)

# Putting data in a pandas dataframe
X = adult.data.features
y = adult.data.targets
data=pd.concat([X,y],axis=1)

In [ ]:
#printing data
data

## Importing the dataset from a folder on your local disk

In [18]:
#importing the dataset as a Pandas DataFrame into Python if the dataset is stored on your local hard disk
# You can download the dataset from the following URL: https://archive.ics.uci.edu/dataset/2/adult
data = pd.read_csv('adult.csv') # Replace the current data path with the data path on your local disk

## Exploring the dataset

In [19]:
# Showing the first 5 rows of the dataset
data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [20]:
# Finding the shape of the data
print(data.shape)

(48842, 15)

In [21]:
# Generate a dataset by randomly extracting 30000 rows (samples)
data_new = data.sample(n=30000, random_state = 48)

In [22]:
# Printing the new dataset
data_new

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
8029,29,Private,216481,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,>50K
45203,36,Private,280570,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,45,United-States,<=50K.
27498,25,?,100903,Bachelors,13,Married-civ-spouse,?,Wife,White,Female,0,0,25,United-States,<=50K
48416,47,Private,145636,Assoc-voc,11,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,0,0,48,United-States,>50K.
43230,33,Private,119422,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,<=50K.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37544,20,Private,166371,HS-grad,9,Never-married,Craft-repair,Other-relative,White,Male,0,0,40,United-States,<=50K.
20482,80,Private,202483,HS-grad,9,Married-spouse-absent,Adm-clerical,Not-in-family,White,Female,0,0,16,United-States,<=50K
39667,20,Private,175808,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K.
40001,25,State-gov,31350,Some-college,10,Never-married,Other-service,Not-in-family,White,Male,0,0,40,United-States,<=50K.
48523,19,Private,239057,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K.

In [23]:
# The indices of different rows in the dataset are currently messy. This happens in many data science projects. Always reindex
# the dataset if you are unsure the indices are correct.
data_new.reset_index(drop=True, inplace=True)

In [24]:
# Checking if the indices are correct
data_new

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,29,Private,216481,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,>50K
1,36,Private,280570,Some-college,10,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,45,United-States,<=50K.
2,25,?,100903,Bachelors,13,Married-civ-spouse,?,Wife,White,Female,0,0,25,United-States,<=50K
3,47,Private,145636,Assoc-voc,11,Married-civ-spouse,Handlers-cleaners,Husband,White,Male,0,0,48,United-States,>50K.
4,33,Private,119422,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,<=50K.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,20,Private,166371,HS-grad,9,Never-married,Craft-repair,Other-relative,White,Male,0,0,40,United-States,<=50K.
29996,80,Private,202483,HS-grad,9,Married-spouse-absent,Adm-clerical,Not-in-family,White,Female,0,0,16,United-States,<=50K
29997,20,Private,175808,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K.
29998,25,State-gov,31350,Some-college,10,Never-married,Other-service,Not-in-family,White,Male,0,0,40,United-States,<=50K.
29999,19,Private,239057,HS-grad,9,Never-married,Craft-repair,Own-child,White,Male,0,0,40,United-States,<=50K.

In [25]:
data

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48837,39,Private,215419,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,Female,0,0,36,United-States,<=50K.
48838,64,NaN,321403,HS-grad,9,Widowed,NaN,Other-relative,Black,Male,0,0,40,United-States,<=50K.
48839,38,Private,374983,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,Male,0,0,50,United-States,<=50K.
48840,44,Private,83891,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,Male,5455,0,40,United-States,<=50K.
48841,35,Self-emp-inc,182148,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,60,United-States,>50K.

In [26]:
# Getting statistical information of the dataset for different columns (features)
data.describe(include="all")

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
count,48842.000000,47879,4.884200e+04,48842,48842.000000,48842,47876,48842,48842,48842,48842.000000,48842.000000,48842.000000,48568,48842
unique,NaN,9,NaN,16,NaN,7,15,6,5,2,NaN,NaN,NaN,42,4
top,NaN,Private,NaN,HS-grad,NaN,Married-civ-spouse,Prof-specialty,Husband,White,Male,NaN,NaN,NaN,United-States,<=50K
freq,NaN,33906,NaN,15784,NaN,22379,6172,19716,41762,32650,NaN,NaN,NaN,43832,24720
mean,38.643585,NaN,1.896641e+05,NaN,10.078089,NaN,NaN,NaN,NaN,NaN,1079.067626,87.502314,40.422382,NaN,NaN
std,13.710510,NaN,1.056040e+05,NaN,2.570973,NaN,NaN,NaN,NaN,NaN,7452.019058,403.004552,12.391444,NaN,NaN
min,17.000000,NaN,1.228500e+04,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,1.000000,NaN,NaN
25%,28.000000,NaN,1.175505e+05,NaN,9.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,40.000000,NaN,NaN
50%,37.000000,NaN,1.781445e+05,NaN,10.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,40.000000,NaN,NaN
75%,48.000000,NaN,2.376420e+05,NaN,12.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,45.000000,NaN,NaN
max,90.000000,NaN,1.490400e+06,NaN,16.000000,NaN,NaN,NaN,NaN,NaN,99999.000000,4356.000000,99.000000,NaN,NaN

In [ ]:
# Droping row with Null values (This topic will be discussed in detail in the next lecture)
data.dropna(inplace=True)

In [ ]:
data

NOTE: As you can see, because a few rows have been dropped, the index numbers don't correspond to the actual row number (the number of rows is 47623 but the last index is 48841). We need to reindex the data

In [ ]:
# reindexing the original data
data.reset_index(drop=True, inplace=True)

In [ ]:
data

In [ ]:
# Getting the number of Null values for different columns
data.isna().sum()

In [ ]:
# Showing the dataset information
data.info()

In [ ]:
data.shape

In [ ]:
# Getting the count of different values in the column "education-num"
data['education-num'].value_counts()

In [ ]:
# Getting the count of different values in the column "education"
data['education'].value_counts()

In [ ]:
# Dropping a column
data = data.drop(['fnlwgt'], axis=1)

In [ ]:
data.shape

In [ ]:
# Getting the number of unique values of a column
data['education'].nunique()

In [ ]:
# Finding how many rows are related to either gender
data['sex'].value_counts()

In [ ]:
# Calculating the average age of different genders in the dataset
data['age'].groupby([data['sex']]).mean()

In [ ]:
# Getting the average age of different genders in the dataset broken down based on their education
data['age'].groupby([data['sex'],data['education']]).mean()

In [ ]:
# Getting the maximum age of different races in the dataset
data['age'].groupby([data['race']]).max()

In [ ]:
# Extracting the age and education columns and creating a new DataFrame using these columns
a=data['age']
b=data['education']
new_data=pd.concat([a,b],axis=1)

In [ ]:
data

* Q10: Write a function that receives the dataset and replace Famle with F and Male with M (please try to write it yourself before checking the answer in the next cell)

In [ ]:
# Solution
def encode_sex(data):
    rows=data.shape[0]
    a=data.loc[:,'sex']
    for i in range(rows):
        if a[i]=="Male":
            data.loc[i,"sex"]="M"
        elif a[i]=="Female":
            data.loc[i,"sex"]="F"
    return data

In [ ]:
# Copying the data
data_copy=data.copy()

In [ ]:
# Applying the encode_sex function to the copied data
data_encoded=encode_sex(data_copy)
data_encoded.head()

In [ ]:
data